import torch
import torch.nn as nn


class WavetableHarmonicSynth(nn.Module):
    """
    Wavetable-optimized harmonic (additive) synthesizer.

    Harmonic amplitudes are packed into single-period wavetables via IFFT,
    then audio is generated by table lookup with linear interpolation.
    Fully vectorized over time frames for efficient training.
    """

    def __init__(
        self,
        n_harmonics: int = 100,
        table_size: int = 2048,
        sample_rate: int = 16000,
        block_size: int = 64,
    ):
        super().__init__()
        self.n_harmonics = n_harmonics
        self.table_size = table_size
        self.sample_rate = sample_rate
        self.block_size = block_size

    def _build_wavetables(self, harmonic_amps: torch.Tensor) -> torch.Tensor:
        """
        Build wavetables for all frames via batched IFFT.

        Args:
            harmonic_amps: [B, T, n_harmonics]

        Returns:
            wavetables: [B, T, table_size] — RMS-normalized waveforms
        """
        B, T, _ = harmonic_amps.shape
        n_bins = self.table_size // 2 + 1
        n_h = min(self.n_harmonics, n_bins - 1)

        spec = torch.zeros(B, T, n_bins, dtype=harmonic_amps.dtype, device=harmonic_amps.device)
        spec[:, :, 1 : n_h + 1] = harmonic_amps[:, :, :n_h]

        # Batched IFFT over all frames: [B*T, table_size]
        spec_flat = spec.reshape(B * T, n_bins)
        wt_flat = torch.fft.irfft(spec_flat, n=self.table_size, dim=-1)
        wt = wt_flat.reshape(B, T, self.table_size)

        rms = torch.sqrt(torch.mean(wt**2, dim=-1, keepdim=True) + 1e-5)
        wt = wt / rms
        return wt

    def forward(self, harmonic_amps: torch.Tensor, f0_hz: torch.Tensor) -> torch.Tensor:
        """
        Synthesize harmonic audio from frame-rate amplitudes and f0.

        Args:
            harmonic_amps: [B, T, n_harmonics]
            f0_hz:         [B, T]

        Returns:
            audio: [B, T * block_size]
        """
        B, T, _ = harmonic_amps.shape
        device = harmonic_amps.device
        dtype = harmonic_amps.dtype

        f0_hz = f0_hz.clamp(min=1.0)
        phase_inc = f0_hz * self.table_size / self.sample_rate  # [B, T] — per sample

        # Build all wavetables at once
        wavetables = self._build_wavetables(harmonic_amps)  # [B, T, table_size]

        # Phase offsets: cumulative sum of phase per frame
        phase_per_frame = self.block_size * phase_inc  # [B, T]
        cum_phase = torch.cumsum(phase_per_frame, dim=1)  # [B, T]
        frame_start = torch.cat(
            [torch.zeros(B, 1, device=device, dtype=dtype), cum_phase[:, :-1]], dim=1
        )  # [B, T]

        # Sample indices for entire batch: [B, T, block_size]
        offsets = torch.arange(self.block_size, device=device, dtype=dtype)
        sample_idx = (
            frame_start.unsqueeze(-1)
            + offsets.view(1, 1, self.block_size)
            * phase_inc.unsqueeze(-1)
        ) % self.table_size

        # Linear interpolation via gather on flattened [B*T, table_size]
        wt_flat = wavetables.reshape(B * T, self.table_size)  # [B*T, table_size]
        n_flat = B * T

        sample_idx_flat = sample_idx.reshape(n_flat, self.block_size)  # [B*T, block_size]
        idx_floor = sample_idx_flat.floor().long()
        idx_ceil = (idx_floor + 1) % self.table_size
        frac = (sample_idx_flat - idx_floor.float()).to(dtype)

        # Gather base indices need offsets for each row
        row_base = torch.arange(n_flat, device=device).unsqueeze(1).expand(-1, self.block_size)
        gather_floor = wt_flat[row_base, idx_floor]
        gather_ceil = wt_flat[row_base, idx_ceil]

        samples = gather_floor * (1.0 - frac) + gather_ceil * frac  # [B*T, block_size]
        audio = samples.reshape(B, T * self.block_size)

        return audio
