import math
import torch
import torch.nn as nn


class WavetableHarmonicSynth(nn.Module):
    """
    Wavetable-optimized harmonic (additive) synthesizer.

    Harmonic amplitudes are packed into single-period wavetables via IFFT,
    then audio is generated by table lookup with linear interpolation.
    Fully vectorized over time frames for efficient training.

    When inharmonicity β > 0, switches to additive synthesis with
    per-harmonic frequency stretching: f_k = k×f0×(1 + β×(k²-1)).
    """

    def __init__(
        self,
        n_harmonics: int = 256,
        table_size: int = 2048,
        sample_rate: int = 16000,
        block_size: int = 64,
    ):
        super().__init__()
        self.n_harmonics = n_harmonics
        self.table_size = table_size
        self.sample_rate = sample_rate
        self.block_size = block_size

    def _build_wavetables(self, harmonic_amps: torch.Tensor) -> torch.Tensor:
        """
        Build wavetables for all frames via batched IFFT.

        Args:
            harmonic_amps: [B, T, n_harmonics]

        Returns:
            wavetables: [B, T, table_size] — RMS-normalized waveforms
        """
        B, T, _ = harmonic_amps.shape
        n_bins = self.table_size // 2 + 1
        n_h = min(self.n_harmonics, n_bins - 1)

        spec = torch.zeros(B, T, n_bins, dtype=harmonic_amps.dtype, device=harmonic_amps.device)
        spec[:, :, 1 : n_h + 1] = harmonic_amps[:, :, :n_h]

        # Batched IFFT over all frames: [B*T, table_size]
        spec_flat = spec.reshape(B * T, n_bins)
        wt_flat = torch.fft.irfft(spec_flat, n=self.table_size, dim=-1)
        wt = wt_flat.reshape(B, T, self.table_size)

        rms = torch.sqrt(torch.mean(wt**2, dim=-1, keepdim=True) + 1e-5)
        wt = wt / rms
        return wt

    def _forward_inharmonic(
        self,
        harmonic_amps: torch.Tensor,
        f0_hz: torch.Tensor,
        phase_start: torch.Tensor | None,
        beta: torch.Tensor,
    ) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
        """
        Additive synthesis with per-harmonic inharmonic frequency stretching.

        f_k = k × f0 × (1 + β_k × (k² - 1))

        Args:
            harmonic_amps: [B, T, n_harmonics]
            f0_hz:         [B, T]
            phase_start:   [B, n_harmonics] radian phases, or None
            beta:          [B, T] or [B, T, n_harmonics] inharmonicity
                           per-harmonic coefficients ∈ [-0.02, 0.02]

        Returns:
            audio: [B, T * block_size]
            (audio, phase_end): if phase_start is provided —
                phase_end is [B, n_harmonics] in radians
        """
        B, T, n_h = harmonic_amps.shape
        device = harmonic_amps.device
        dtype = harmonic_amps.dtype
        track_phase = phase_start is not None

        f0_hz = f0_hz.clamp(min=1.0)  # [B, T]

        # Harmonic indices k = 1, 2, ..., n_h
        k = torch.arange(1, n_h + 1, device=device, dtype=dtype)  # [n_h]
        k_sq = k * k

        # Inharmonic frequencies: f_k = k × f0 × (1 + β_k × (k² - 1))
        f0 = f0_hz.unsqueeze(-1)  # [B, T, 1]
        b = beta
        while b.dim() < 2:
            b = b.unsqueeze(0)
        if b.dim() == 2:
            # Per-frame scalar β [B, T]: broadcast to all harmonics
            b = b.unsqueeze(-1)  # [B, T, 1]
        elif b.shape[-1] == 1:
            # Per-frame scalar already 3D [B, T, 1]: ready for broadcast
            pass
        # else: per-harm β [B, T, n_h]: use as-is
        inharm_factor = 1.0 + b * (k_sq - 1.0)  # broadcast to [B, T, n_h]
        inharm_factor = inharm_factor.clamp(min=0.01)  # prevent negative frequencies
        freqs = k * f0 * inharm_factor  # [B, T, n_h]

        # Phase increment per sample: 2π × f_k / sample_rate
        phase_inc = 2.0 * math.pi * freqs / self.sample_rate  # [B, T, n_h]

        # Cumulative phase at start of each frame
        phase_per_frame = self.block_size * phase_inc  # [B, T, n_h]
        cum_phase = torch.cumsum(phase_per_frame, dim=1)  # [B, T, n_h]
        frame_start_phase = torch.cat(
            [torch.zeros(B, 1, n_h, device=device, dtype=dtype), cum_phase[:, :-1, :]],
            dim=1,
        )  # [B, T, n_h]

        if track_phase:
            # phase_start is [B, n_h] in radians
            frame_start_phase = frame_start_phase + phase_start.unsqueeze(1)

        # Sample offsets within frame: [1, 1, 1, block_size]
        offsets = torch.arange(self.block_size, device=device, dtype=dtype)

        # Per-sample phases: [B, T, n_h, block_size]
        phases = (
            frame_start_phase.unsqueeze(-1)
            + offsets.view(1, 1, 1, self.block_size) * phase_inc.unsqueeze(-1)
        )

        # Sum of weighted sinusoids across harmonics
        samples = torch.sin(phases) * harmonic_amps.unsqueeze(-1)  # [B, T, n_h, block_size]
        audio = samples.sum(dim=2)  # [B, T, block_size]

        # RMS-normalize per frame to match wavetable path output level
        audio_2d = audio.reshape(B * T, self.block_size)
        rms = torch.sqrt(torch.mean(audio_2d ** 2, dim=-1, keepdim=True) + 1e-5)
        audio_2d = audio_2d / rms
        audio = audio_2d.reshape(B, T * self.block_size)

        if track_phase:
            phase_end = (frame_start_phase[:, -1, :] + phase_per_frame[:, -1, :]) % (2.0 * math.pi)
            return audio, phase_end

        return audio

    def forward(
        self,
        harmonic_amps: torch.Tensor,
        f0_hz: torch.Tensor,
        phase_start: torch.Tensor | None = None,
        inharmonicity: torch.Tensor | float | None = None,
    ) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
        """
        Synthesize harmonic audio from frame-rate amplitudes and f0.

        Args:
            harmonic_amps:  [B, T, n_harmonics]
            f0_hz:          [B, T]
            phase_start:    [B] for harmonic, [B, n_harmonics] for inharmonic.
                            When provided, returns (audio, phase_end) for
                            continuous phase tracking across calls.
            inharmonicity:  [B, T] or scalar β ∈ [0, 0.01]. When >0,
                            stretches harmonic frequencies:
                            f_k = k×f0×(1 + β×(k²-1)).

        Returns:
            audio: [B, T * block_size]
            (audio, phase_end): if phase_start is provided
        """
        B, T, n_h = harmonic_amps.shape

        # Inharmonic path
        if inharmonicity is not None:
            beta = inharmonicity
            if isinstance(beta, (int, float)):
                if beta == 0.0:
                    pass  # fall through to harmonic path
                else:
                    beta = torch.full((B, T), float(beta), device=harmonic_amps.device, dtype=harmonic_amps.dtype)
                    return self._forward_inharmonic(harmonic_amps, f0_hz, phase_start, beta)
            else:
                if beta.abs().max() > 0:
                    return self._forward_inharmonic(harmonic_amps, f0_hz, phase_start, beta.to(harmonic_amps.dtype))

        # Harmonic (wavetable) path
        device = harmonic_amps.device
        dtype = harmonic_amps.dtype
        track_phase = phase_start is not None

        f0_hz = f0_hz.clamp(min=1.0)
        phase_inc = f0_hz * self.table_size / self.sample_rate  # [B, T] — per sample

        # Build all wavetables at once
        wavetables = self._build_wavetables(harmonic_amps)  # [B, T, table_size]

        # Phase offsets: cumulative sum of phase per frame
        phase_per_frame = self.block_size * phase_inc  # [B, T]
        cum_phase = torch.cumsum(phase_per_frame, dim=1)  # [B, T]
        frame_start = torch.cat(
            [torch.zeros(B, 1, device=device, dtype=dtype), cum_phase[:, :-1]], dim=1
        )  # [B, T]

        # Apply external phase start offset
        if track_phase:
            frame_start = (frame_start + phase_start.unsqueeze(1)) % self.table_size  # type: ignore[arg-type]

        # Sample indices for entire batch: [B, T, block_size]
        offsets = torch.arange(self.block_size, device=device, dtype=dtype)
        sample_idx = (
            frame_start.unsqueeze(-1)
            + offsets.view(1, 1, self.block_size)
            * phase_inc.unsqueeze(-1)
        ) % self.table_size

        # Linear interpolation via gather on flattened [B*T, table_size]
        wt_flat = wavetables.reshape(B * T, self.table_size)  # [B*T, table_size]
        n_flat = B * T

        sample_idx_flat = sample_idx.reshape(n_flat, self.block_size)  # [B*T, block_size]
        idx_floor = sample_idx_flat.floor().long()
        idx_ceil = (idx_floor + 1) % self.table_size
        frac = (sample_idx_flat - idx_floor.float()).to(dtype)

        # Gather base indices need offsets for each row
        row_base = torch.arange(n_flat, device=device).unsqueeze(1).expand(-1, self.block_size)
        gather_floor = wt_flat[row_base, idx_floor]
        gather_ceil = wt_flat[row_base, idx_ceil]

        samples = gather_floor * (1.0 - frac) + gather_ceil * frac  # [B*T, block_size]
        audio = samples.reshape(B, T * self.block_size)

        if track_phase:
            phase_end = (frame_start[:, -1] + phase_per_frame[:, -1]) % self.table_size  # type: ignore[index]
            return audio, phase_end  # type: ignore[return-value]

        return audio
